version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "5.0.x"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    commit-message:
      prefix: "(v5.0.x)"
    target-branch: "5.0.x"
    ignore:
      - dependency-name: "org.springframework.boot"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      - dependency-name: "org.springframework.boot:spring-boot-dependencies"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      - dependency-name: "org.springframework.cloud.contract"
        update-types:
          -  "version-update:semver-major"
          -  "version-update:semver-minor"
      - dependency-name: "org.springframework.cloud:spring-cloud-contract-dependencies"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    commit-message:
      prefix: "(v4.5.x)"
    target-branch: "4.5.x"
    ignore:
      - dependency-name: "org.springframework.boot"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      - dependency-name: "org.springframework.boot:spring-boot-dependencies"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      - dependency-name: "org.springframework.cloud.contract"
        update-types:
          -  "version-update:semver-major"
          -  "version-update:semver-minor"
      - dependency-name: "org.springframework.cloud:spring-cloud-contract-dependencies"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"