== Contributing

Spring Cloud is released under the non-restrictive Apache 2.0 license,
and follows a very standard Github development process, using Github
tracker for issues and merging pull requests into main. If you want
to contribute even something trivial please do not hesitate, but
follow the guidelines below.

=== Developer Certificate of Origin
All commits must include a *Signed-off-by* trailer at the end of each commit message to
indicate that the contributor agrees to the Developer Certificate of Origin. For details,
see
https://spring.io/blog/2025/01/06/hello-dco-goodbye-cla-simplifying-contributions-to-spring[Hello
DCO, Goodbye CLA: Simplifying Contributions to Spring].

=== Code of Conduct
This project adheres to the Spring Cloud organization-wide
https://github.com/spring-cloud/.github/blob/main/CODE_OF_CONDUCT.md[code of conduct]. By
participating, you are expected to uphold this code. Please report unacceptable behavior to
code-of-conduct@spring.io.

=== Code Conventions and Housekeeping
None of these is essential for a pull request, but they will all help.  They can also be
added after the original pull request but before a merge.

* Use the https://github.com/spring-io/spring-javaformat[spring-javaformat] code format
  conventions used by this project; run `./gradlew format` to apply them before submitting
  a pull request.
* Make sure all new `.java` files to have a simple Javadoc class comment with at least an
  `@author` tag identifying you, and preferably at least a paragraph on what the class is
  for.
* Add the Apache 2.0 license header comment to all new `.java` files (copy from existing
  files in the project)
* Add yourself as an `@author` to the .java files that you modify substantially (more
  than cosmetic changes).
* Add some Javadocs.
* A few unit tests would help a lot as well -- someone has to do it.
* If no-one else is using your branch, please rebase it against the current main (or
  other target branch in the main project).
* When writing a commit message please follow https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html[these conventions],
  if you are fixing an existing issue please add `Fixes gh-XXXX` at the end of the commit
  message (where XXXX is the issue number).

