org.gradle.caching=true
org.gradle.parallel=true

version=4.5.1-SNAPSHOT

#Gradle plugins
springBootVersion=3.5.3
springJavaFormatVersion=0.0.46
asciidoctorVersion=4.0.3
nohttpVersion=0.0.11

# external dependencies
beanUtilsVersion=1.11.0

#test dependencies
springCloudContractVersion=4.3.0
javaHamcrestVersion=2.0.0.0
equalsVerifierVersion=4.0
findbugsVersion=3.0.1u2
wiremockStandaloneVersion=3.0.1

# static analysis
blockHoundVersion=1.0.13.RELEASE
junitPlatformLauncherVersion=1.7.0
