image:https://build.spring.io/plugins/servlet/wittified/build-status/CLOUD-SCCFSB["Bamboo", link="https://build.spring.io/browse/CLOUD-SCCFSB"] image:https://github.com/spring-cloud/spring-cloud-open-service-broker/workflows/Java%208/badge.svg["GitHub Actions", link="https://github.com/spring-cloud/spring-cloud-open-service-broker/actions?query=workflow%3A%22Java+8%22"]
image:https://github.com/spring-cloud/spring-cloud-open-service-broker/workflows/Java%2011/badge.svg["GitHub Actions", link="https://github.com/spring-cloud/spring-cloud-open-service-broker/actions?query=workflow%3A%22Java+11%22"]
image:https://github.com/spring-cloud/spring-cloud-open-service-broker/workflows/Java%2014/badge.svg["GitHub Actions", link="https://github.com/spring-cloud/spring-cloud-open-service-broker/actions?query=workflow%3A%22Java+14%22"]
image:https://circleci.com/gh/spring-cloud/spring-cloud-open-service-broker.svg?style=svg["CircleCI", link="https://circleci.com/gh/spring-cloud/spring-cloud-open-service-broker"]
image:https://api.codacy.com/project/badge/Grade/6fb04712acd14a898ecf504d545d1400["Codacy code quality", link="https://www.codacy.com/app/scottfrederick/spring-cloud-open-service-broker?utm_source=github.com&amp;utm_medium=referral&amp;utm_content=spring-cloud/spring-cloud-open-service-broker&amp;utm_campaign=Badge_Grade"]
image:https://codecov.io/gh/spring-cloud/spring-cloud-open-service-broker/branch/master/graph/badge.svg["Codecov", link="https://codecov.io/gh/spring-cloud/spring-cloud-open-service-broker/branch/master"]

= Overview

Spring Cloud Open Service Broker is a framework for building https://projects.spring.io/spring-boot/[Spring Boot] applications that implement the https://www.openservicebrokerapi.org/[Open Service Broker API].

[NOTE]
This project was formerly named *Spring Cloud - Cloud Foundry Service Broker*. View the https://github.com/spring-cloud/spring-cloud-open-service-broker/tree/1.0.x[1.0.x] branch of this repository for information on using the released versions of the project with artifacts using that name.

== Version Compatibility

The following table describes the version compatibility matrix for the various releases of Spring Cloud Open Service Broker.

[%header,cols=4*]
|===
|Spring Cloud Open Service Broker |https://github.com/openservicebrokerapi/servicebroker[Open Service Broker API] |https://projects.spring.io/spring-boot/[Spring Boot] |https://projects.spring.io/spring-framework/[Spring Framework]
|3.4.x |2.16 |2.4.x |5.3.x
|3.3.x |2.15 |2.4.x |5.3.x
|3.2.x |2.15 |2.3.x |5.2.x
|3.1.x |2.15 |2.2.x |5.2.x
|3.0.x |2.14 |2.1.x |5.1.x
|2.1.x |2.14 |2.0.x |5.0.x
|===

[NOTE]
Spring WebFlux and Spring MVC are both supported in version 3.0 and later

== Getting Started

See the https://spring.io/projects/spring-cloud-open-service-broker/[project site] and https://docs.spring.io/spring-cloud-open-service-broker/docs/current/reference/[reference documentation] to get started building a service broker using this framework.

=== Gradle Dependencies

```
implementation("org.springframework.cloud:spring-cloud-starter-open-service-broker:3.2.0")
```

=== Maven Dependencies:

```
<dependency>
  <groupId>org.springframework.cloud</groupId>
  <artifactId>spring-cloud-starter-open-service-broker</artifactId>
  <version>3.2.0</version>
</dependency>
```

See the https://github.com/spring-cloud/spring-cloud-open-service-broker/wiki/2.0-Migration-Guide[migration guide] if you are migrating a project from `Spring Cloud - Cloud Foundry Service Broker` 1.x to `Spring Cloud Open Service Broker` 2.x.

== Build

This project requires Java 8.

The project is built with Gradle. The https://docs.gradle.org/current/userguide/gradle_wrapper.html[Gradle wrapper] allows you to build the project on multiple platforms and even if you do not have Gradle installed; run it in place of the `gradle` command (as `./gradlew`) from the root of the main project directory.

=== Compile the project and run tests

    ./gradlew build

Deploy the artifacts to your local maven repository:

    ./gradlew publishToMavenLocal

== Working with the code
If you don't have an IDE preference we would recommend that you use
https://spring.io/tools[Spring Tool Suite] or
https://eclipse.org[Eclipse] when working with the code. We use the
https://eclipse.org/m2e/[m2eclipse] eclipse plugin for maven support. Other IDEs and tools
should also work without issue as long as they use Maven 3.3.3 or better.

== Contributing

Spring Cloud is released under the non-restrictive Apache 2.0 license,
and follows a very standard Github development process, using Github
tracker for issues and merging pull requests into master. If you want
to contribute even something trivial please do not hesitate, but
follow the guidelines below.

=== Sign the Contributor License Agreement
Before we accept a non-trivial patch or pull request we will need you to sign the
https://cla.pivotal.io/sign/spring[Contributor License Agreement].
Signing the contributor's agreement does not grant anyone commit rights to the main
repository, but it does mean that we can accept your contributions, and you will get an
author credit if we do.  Active contributors might be asked to join the core team, and
given the ability to merge pull requests.

=== Code of Conduct
This project adheres to the Contributor Covenant link:/CODE_OF_CONDUCT.adoc[code of
conduct]. By participating, you  are expected to uphold this code. Please report
unacceptable behavior to spring-code-of-conduct@pivotal.io.

=== Code Conventions and Housekeeping
None of these is essential for a pull request, but they will all help.  They can also be
added after the original pull request but before a merge.

* Use the Spring Framework code format conventions. If you use Eclipse
  you can import formatter settings using the
  `eclipse-code-formatter.xml` file from the
  https://raw.githubusercontent.com/spring-cloud/spring-cloud-build/master/spring-cloud-dependencies-parent/eclipse-code-formatter.xml[Spring
  Cloud Build] project. If using IntelliJ, you can use the
  https://plugins.jetbrains.com/plugin/6546[Eclipse Code Formatter
  Plugin] to import the same file.
* Make sure all new `.java` files to have a simple Javadoc class comment with at least an
  `@author` tag identifying you, and preferably at least a paragraph on what the class is
  for.
* Add the ASF license header comment to all new `.java` files (copy from existing files
  in the project)
* Add yourself as an `@author` to the .java files that you modify substantially (more
  than cosmetic changes).
* Add some Javadocs and, if you change the namespace, some XSD doc elements.
* A few unit tests would help a lot as well -- someone has to do it.
* If no-one else is using your branch, please rebase it against the current master (or
  other target branch in the main project).
* When writing a commit message please follow https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html[these conventions],
  if you are fixing an existing issue please add `Fixes #XXXX` at the end of the commit
  message (where XXXX is the GitHub issue number).

