image:https://github.com/spring-cloud/spring-cloud-open-service-broker/actions/workflows/java-17.yml/badge.svg["GitHub Actions", link="https://github.com/spring-cloud/spring-cloud-open-service-broker/actions/workflows/java-17.yml"]
image:https://github.com/spring-cloud/spring-cloud-open-service-broker/actions/workflows/java-21.yml/badge.svg["GitHub Actions", link="https://github.com/spring-cloud/spring-cloud-open-service-broker/actions/workflows/java-21.yml"]
image:https://github.com/spring-cloud/spring-cloud-open-service-broker/actions/workflows/java-25.yml/badge.svg["GitHub Actions", link="https://github.com/spring-cloud/spring-cloud-open-service-broker/actions/workflows/java-25.yml"]

= Overview

Spring Cloud Open Service Broker is a framework for building https://projects.spring.io/spring-boot/[Spring Boot] applications that implement the https://www.openservicebrokerapi.org/[Open Service Broker API]. Both https://docs.spring.io/spring-framework/reference/web/webflux.html[Spring WebFlux] and https://docs.spring.io/spring-framework/reference/web/webmvc.html[Spring MVC] web frameworks are supported in Spring Cloud Open Service Broker.

== Version Compatibility

The following table describes the version compatibility matrix for the various releases of Spring Cloud Open Service Broker. Please note that certain Spring Boot versions have reached https://spring.io/projects/spring-boot#support[end of support]. We recommend upgrading to a version of Spring Cloud Open Service Broker that supports a newer version of Spring Boot.

[%header,cols=5*]
|===
|https://spring.io/projects/spring-cloud-open-service-broker[Spring Cloud Open Service Broker]|https://github.com/openservicebrokerapi/servicebroker[Open Service Broker API] |https://spring.io/projects/spring-boot[Spring Boot] |https://projects.spring.io/spring-framework/[Spring Framework]|JDK
|5.1.x |2.16 |4.1.x |7.0.x|17
|5.0.x |2.16 |4.0.x |7.0.x|17
|4.5.x |2.16 |3.5.x |6.2.x|17
|4.4.x |2.16 |3.4.x |6.2.x|17
|4.3.x |2.16 |3.3.x |6.1.x|17
|4.2.x |2.16 |3.2.x |6.1.x|17
|3.6.x |2.16 |2.7.x |5.3.x|8
|===

== Getting Started

See the https://spring.io/projects/spring-cloud-open-service-broker/[project site] and https://docs.spring.io/spring-cloud-open-service-broker/docs/current/reference/[reference documentation] to get started building a service broker using this framework.

=== Gradle Dependencies

```
implementation("org.springframework.cloud:spring-cloud-starter-open-service-broker:${current-version}")
```

=== Maven Dependencies:

```
<dependency>
  <groupId>org.springframework.cloud</groupId>
  <artifactId>spring-cloud-starter-open-service-broker</artifactId>
  <version>${current-version}</version>
</dependency>
```

== Build

This project requires Java 17.

The project is built with Gradle. The https://docs.gradle.org/current/userguide/gradle_wrapper.html[Gradle wrapper] allows you to build the project on multiple platforms and even if you do not have Gradle installed; run it in place of the `gradle` command (as `./gradlew`) from the root of the main project directory.

=== Compile the project and run tests

    ./gradlew build

Deploy the artifacts to your local maven repository:

    ./gradlew publishToMavenLocal

Perform all checks, including checkstyle, unit tests, and contract tests:

    ./gradlew check

Format source according to the https://github.com/spring-io/spring-javaformat[spring-javaformat] project standards

    ./gradlew format

Run only unit tests:

    ./gradlew test

Run only contract tests:

    ./gradlew contractTest

== Working with the code

If you don't have an IDE preference we would recommend that you use
https://spring.io/tools[Spring Tools for VS Code or Eclipse] when working with the code.
This project is built with Gradle (see the Build section above), so an IDE with Gradle
support, such as Spring Tools for VS Code, Eclipse, or IntelliJ IDEA, should import the
project without issue.

== Contributing

Spring Cloud is released under the non-restrictive Apache 2.0 license,
and follows a very standard Github development process, using Github
tracker for issues and merging pull requests into main. If you want
to contribute even something trivial please do not hesitate, but
follow the guidelines below.

=== Developer Certificate of Origin

All commits must include a *Signed-off-by* trailer at the end of each commit message to
indicate that the contributor agrees to the Developer Certificate of Origin. For details,
see
https://spring.io/blog/2025/01/06/hello-dco-goodbye-cla-simplifying-contributions-to-spring[Hello
DCO, Goodbye CLA: Simplifying Contributions to Spring].

=== Code of Conduct

This project adheres to the Spring Cloud organization-wide
https://github.com/spring-cloud/.github/blob/main/CODE_OF_CONDUCT.md[code of conduct]. By
participating, you are expected to uphold this code. Please report unacceptable behavior to
code-of-conduct@spring.io.

=== Code Conventions and Housekeeping

None of these is essential for a pull request, but they will all help.  They can also be
added after the original pull request but before a merge.

* Use the https://github.com/spring-io/spring-javaformat[spring-javaformat] code format
  conventions used by this project; run `./gradlew format` to apply them before submitting
  a pull request.
* Make sure all new `.java` files to have a simple Javadoc class comment with at least an
  `@author` tag identifying you, and preferably at least a paragraph on what the class is
  for.
* Add the Apache 2.0 license header comment to all new `.java` files (copy from existing
  files in the project)
* Add yourself as an `@author` to the .java files that you modify substantially (more
  than cosmetic changes).
* Add some Javadocs.
* A few unit tests would help a lot as well -- someone has to do it.
* If no-one else is using your branch, please rebase it against the current main (or
  other target branch in the main project).
* When writing a commit message please follow https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html[these conventions],
  if you are fixing an existing issue please add `Fixes #XXXX` at the end of the commit
  message (where XXXX is the GitHub issue number).

