:examples-dir: ../../src/test/java/com/example/servicebroker/
[[service-broker-security]]
== Service Broker Security

Authentication and authorization of service broker endpoints is not specified in the Open Service Broker API specification, but some platforms require or let https://en.wikipedia.org/wiki/Basic_access_authentication[basic authentication] or https://oauth.net/2/[OAuth2] credentials be provided when a service broker is registered to the platform.

The Spring Cloud Open Service Broker project does not implement any security configuration.
Service broker application endpoints can be secured with https://projects.spring.io/spring-security/[Spring Security]
and https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-security.html[Spring Boot security configuration]
by applying security to application endpoints with the path-matching pattern: `/v2/**`.

=== Example Configuration

The following example implements a security configuration in a https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html[Spring MVC] i.e blocking webstack. Similar config for a https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html[Spring WebFlux] reactive stack is necessary, see https://docs.spring.io/spring-security/site/docs/current/reference/html5/#minimal-webflux-security-configuration[Spring security webflux support]

====
[source,java,%autofit]
----
include::{examples-dir}/ExampleSecurityConfig.java[]
----
====
