/*
 * Copyright 2002-2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import org.springframework.boot.gradle.plugin.SpringBootPlugin

plugins {
	alias(libs.plugins.spring.boot) apply false
}

description = "Spring Cloud Open Service Broker Auto-Configuration"

dependencies {
	// BOM imports - The versions used in these files will override any other versions found in the graph
	implementation platform(SpringBootPlugin.BOM_COORDINATES)
	annotationProcessor platform(SpringBootPlugin.BOM_COORDINATES)

	api project(':spring-cloud-open-service-broker-core')
	compileOnly 'org.springframework.boot:spring-boot-starter-webmvc'
	compileOnly 'org.springframework.boot:spring-boot-starter-webflux'
	annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
	annotationProcessor 'org.springframework.boot:spring-boot-autoconfigure-processor'
	testImplementation project(path: ':spring-cloud-open-service-broker-core', configuration: 'testOutput')
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-webflux-test'
	testImplementation libs.blockhound.junit.platform
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testRuntimeOnly 'jakarta.servlet:jakarta.servlet-api'
	testImplementation 'org.mockito:mockito-core'
	testImplementation 'org.assertj:assertj-core'
	testImplementation 'org.apache.commons:commons-lang3'
}

configurations {
	testOutput
}

artifacts {
	testOutput testsJar
}

compileJava.dependsOn(processResources)
