---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: ((dockerhub-mirror-registry))/concourse/oci-build-task
    tag: 0.11.1

inputs:
  - name: source

outputs:
  - name: image

run:
  path: build

params:
  CONTEXT:
