---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: ((dockerhub-mirror-registry))/springio/concourse-release-scripts
    tag: '0.3.4'
inputs:
  - name: git-repo
  - name: artifactory-repo
outputs:
  - name: version
params:
  RELEASE_TYPE: ((release-type))
  ARTIFACTORY_SERVER: ((artifactory-server))
  ARTIFACTORY_USERNAME: ((artifactory-username))
  ARTIFACTORY_PASSWORD: ((artifactory-password))
run:
  path: git-repo/ci/scripts/promote.sh
