---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: ((open-service-broker-virtual-docker-registry))/springio/concourse-release-scripts
    username: ((broadcom-jfrog-artifactory-robot-account.username))
    password: ((broadcom-jfrog-artifactory-robot-account.password))
    tag: '0.3.4'
inputs:
  - name: git-repo
  - name: artifactory-repo
outputs:
  - name: version
params:
  RELEASE_TYPE: ((release-type))
  ARTIFACTORY_SERVER: ((artifactory-server))
  ARTIFACTORY_USERNAME: ((artifactory-username))
  ARTIFACTORY_PASSWORD: ((artifactory-password))
run:
  path: git-repo/ci/scripts/promote.sh
