---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: ((open-service-broker-virtual-docker-registry))/springio/concourse-release-scripts
    username: ((broadcom-jfrog-artifactory-robot-account.username))
    password: ((broadcom-jfrog-artifactory-robot-account.password))
    tag: '0.3.4'
inputs:
  - name: git-repo
  - name: artifactory-repo
params:
  SONATYPE_URL: ((sonatype-url))
  SONATYPE_USERNAME: ((sonatype-user-token))
  SONATYPE_PASSWORD: ((sonatype-user-token-password))
  SONATYPE_STAGING_PROFILE_ID: ((sonatype-staging-profile-id))
run:
  path: git-repo/ci/scripts/sync-to-maven-central.sh
