[[implementing-service-instances]]
== Service Binding & Unbinding

Services can optionally provide functionality for {osbspec}#binding[creating bindings] for applications to consume.
Services that support binding must advertise the fact in their {javadoc}/org/springframework/cloud/servicebroker/model/catalog/ServiceDefinition.html#isBindable--[Service Definition]

Service bindings are typically used to expose credentials to an application. They can also be used to expose route, logging and volume services.

=== Creating a Service Binding
The {javadoc-services}ServiceInstanceBindingService.html[createServiceInstanceBinding()]
method must be overridden to implement service binding creation behavior

A typical flow for creating a service binding is;

* Check if the binding already exists with the same parameters. If it did then return `bindingExisted` in the response
* Create the requested resource in the underlying platform (credential, route or volume). Parameters may be included in the request
to specify how the resource is created.
* Build a response with details of the binding.

Implementations should be mindful of returning credentials in clear text and instead
return a reference that enables the consumer to retrieve the credential in secure way.

=== Retrieving Service Bindings
The {javadoc-services}ServiceInstanceBindingService.html[getServiceInstanceBinding()]
method must be overridden to implement service binding retrieval behavior
Implementations need to retrieve the state of bindings owned by the service. Binding
state could be retrieved from the underlying platform or from another datastore.

=== Deleting a Service Binding
The {javadoc-services}ServiceInstanceBindingService.html[deleteServiceInstanceBinding()]
method must be overridden to implement service binding deletion behavior
A binding deletion operation will need to delete any platform resources associated
with the binding and any persisted state.

=== Example implementation

[source,java,%autofit]
----
include::{examplesdir}/ExampleServiceBinding.java[]
----